name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOWNLOAD_TOKEN: ${{ secrets.DOWNLOAD_TOKEN }}
          CZDB_TOKEN: ${{ secrets.CZDB_TOKEN }}
        run: |
          pnpm i
          pnpm run build
